# Site settings
title: Minimal Monkey - Stephen Burgess
email: steve@minimalmonkey.com
description: "Hello my name is Stephen Burgess."
tagline: "Hello my name is Stephen Burgess"
baseurl: ""
url: "http://minimalmonkey.com"
twitter_username: minimalmonkey
github_username:  minimalmonkey

# Build settings
markdown: kramdown
permalink: /:categories/:title/
exclude: ['README.md', 'package.json', 'gulpfile.js', 'node_modules']
