# Site settings
title: Minimal Monkey - Stephen Burgess
email: steve@minimalmonkey.com
description: "Hello my name is Stephen Burgess."
tagline: "Hello my name is Stephen Burgess"
baseurl: ""
# url: "http://minimalmonkey.com"
url: "http://minimalmonkeyblog.s3-website-us-west-2.amazonaws.com"
twitter_username: minimalmonkey
github_username:  minimalmonkey
bug_report: "https://github.com/minimalmonkey/minimalmonkey.github.io/issues"
images_root: "http://minimalmonkeyblog.s3-website-us-west-2.amazonaws.com"

# Pagination
per_page: 10
gems: [jekyll-paginate]
paginate: 10 # should match per_page above
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
exclude: ['README.md', 'LICENSE', 'package.json', 'gulpfile.js', 'node_modules', 'archive', 'images']
